### PR TITLE
FIX getSelfHost no longer returns a port number

### LINKED ISSUE #153: Custom port along with X-Forwared-Port would cause double port concatination
I haven't verified this but it appears that a host that uses a custom port in conjunction with an `X-Forwarded-Port` header would lead to double port concatenation.

A port is appended to the host if set via headers (https://github.com/onelogin/php-saml/blob/570a5d9cc42a1a205355b9212bd182fbe35404d9/lib/Saml2/Utils.php#L281-L304) but `getSelfHost` appears to return a host with a port if it exists (https://github.com/onelogin/php-saml/blob/570a5d9cc42a1a205355b9212bd182fbe35404d9/lib/Saml2/Utils.php#L311-L334)

A decision needs to be made about which takes precedence and it should be consistently applied

### PR DESCRIPTION
**Pull request by dhensby**
Fixes #153 

- Make sure getSelfHost doesn't return a port
- Added getSelfPort to normalise port fetching

### CODE REVIEW

File: lib/Saml2/Utils.php [hunk 1]
```diff
@@ -322,26 +315,60 @@ public static function getSelfHost()
...
+     * @return null|string The port number used for the request
+     */
+    public static function getSelfPort()
+    {
+        $portnumber = null;
+        if (isset($_SERVER["HTTP_X_FORWARDED_PORT"])) {
+            $portnumber = $_SERVER["HTTP_X_FORWARDED_PORT"];
+        } else if (isset($_SERVER["SERVER_PORT"])) {
+            $portnumber = $_SERVER["SERVER_PORT"];
+        }
```
Comment (pitbulk) [inline lib/Saml2/Utils.php]: can you set the else after the }

```
} else
```

if not phpcs fails.

Comment (dhensby) [inline lib/Saml2/Utils.php]: done

**Comment by dhensby** [comment]
@pitbulk I've made this change based on your feedback. Is it ok to go in or so you have some concerns?
